import * as LucideIcons from "lucide-react";
import type { IconName } from "@shared/schema";
import { cn } from "@/lib/utils";

interface DynamicIconProps {
  name: IconName | string;
  className?: string;
}

export function DynamicIcon({ name, className }: DynamicIconProps) {
  const iconMap: Record<string, React.ElementType> = {
    Globe: LucideIcons.Globe,
    Home: LucideIcons.Home,
    Star: LucideIcons.Star,
    Heart: LucideIcons.Heart,
    Bookmark: LucideIcons.Bookmark,
    Folder: LucideIcons.Folder,
    File: LucideIcons.File,
    Code: LucideIcons.Code,
    Terminal: LucideIcons.Terminal,
    Database: LucideIcons.Database,
    Server: LucideIcons.Server,
    Cloud: LucideIcons.Cloud,
    Monitor: LucideIcons.Monitor,
    Smartphone: LucideIcons.Smartphone,
    Laptop: LucideIcons.Laptop,
    Wifi: LucideIcons.Wifi,
    Lock: LucideIcons.Lock,
    Key: LucideIcons.Key,
    Shield: LucideIcons.Shield,
    Settings: LucideIcons.Settings,
    Cog: LucideIcons.Cog,
    Tool: LucideIcons.Wrench,
    Wrench: LucideIcons.Wrench,
    Hammer: LucideIcons.Hammer,
    Zap: LucideIcons.Zap,
    Lightning: LucideIcons.Zap,
    Flame: LucideIcons.Flame,
    Sun: LucideIcons.Sun,
    Moon: LucideIcons.Moon,
    CloudSun: LucideIcons.CloudSun,
    Music: LucideIcons.Music,
    Video: LucideIcons.Video,
    Image: LucideIcons.Image,
    Camera: LucideIcons.Camera,
    Mic: LucideIcons.Mic,
    Headphones: LucideIcons.Headphones,
    Speaker: LucideIcons.Speaker,
    Mail: LucideIcons.Mail,
    MessageSquare: LucideIcons.MessageSquare,
    Send: LucideIcons.Send,
    Inbox: LucideIcons.Inbox,
    Bell: LucideIcons.Bell,
    Calendar: LucideIcons.Calendar,
    Clock: LucideIcons.Clock,
    MapPin: LucideIcons.MapPin,
    Navigation: LucideIcons.Navigation,
    Compass: LucideIcons.Compass,
    Map: LucideIcons.Map,
    Users: LucideIcons.Users,
    User: LucideIcons.User,
    UserPlus: LucideIcons.UserPlus,
    Building: LucideIcons.Building,
    Store: LucideIcons.Store,
    ShoppingCart: LucideIcons.ShoppingCart,
    CreditCard: LucideIcons.CreditCard,
    DollarSign: LucideIcons.DollarSign,
    Wallet: LucideIcons.Wallet,
    TrendingUp: LucideIcons.TrendingUp,
    BarChart: LucideIcons.BarChart,
    PieChart: LucideIcons.PieChart,
    Activity: LucideIcons.Activity,
    Target: LucideIcons.Target,
    Award: LucideIcons.Award,
    Gift: LucideIcons.Gift,
    Package: LucideIcons.Package,
    Truck: LucideIcons.Truck,
    Plane: LucideIcons.Plane,
    Car: LucideIcons.Car,
    Bike: LucideIcons.Bike,
    Train: LucideIcons.Train,
    Coffee: LucideIcons.Coffee,
    Utensils: LucideIcons.Utensils,
    Pizza: LucideIcons.Pizza,
    Apple: LucideIcons.Apple,
    Leaf: LucideIcons.Leaf,
    Tree: LucideIcons.Trees,
    Flower: LucideIcons.Flower,
    Book: LucideIcons.Book,
    Newspaper: LucideIcons.Newspaper,
    FileText: LucideIcons.FileText,
    ClipboardList: LucideIcons.ClipboardList,
    CheckSquare: LucideIcons.CheckSquare,
    List: LucideIcons.List,
    Grid: LucideIcons.Grid3X3,
    Layers: LucideIcons.Layers,
    Box: LucideIcons.Box,
    Cube: LucideIcons.Box,
    Hexagon: LucideIcons.Hexagon,
    Circle: LucideIcons.Circle,
    Square: LucideIcons.Square,
    Triangle: LucideIcons.Triangle,
    Link: LucideIcons.Link,
    ExternalLink: LucideIcons.ExternalLink,
    Share: LucideIcons.Share,
    Download: LucideIcons.Download,
    Upload: LucideIcons.Upload,
    Refresh: LucideIcons.RefreshCw,
    Search: LucideIcons.Search,
    Eye: LucideIcons.Eye,
    EyeOff: LucideIcons.EyeOff,
    Edit: LucideIcons.Edit,
    Trash: LucideIcons.Trash2,
    Plus: LucideIcons.Plus,
    Minus: LucideIcons.Minus,
    X: LucideIcons.X,
    Check: LucideIcons.Check,
    Github: LucideIcons.Github,
    Gitlab: LucideIcons.Gitlab,
    Twitter: LucideIcons.Twitter,
    Linkedin: LucideIcons.Linkedin,
    Facebook: LucideIcons.Facebook,
    Instagram: LucideIcons.Instagram,
    Youtube: LucideIcons.Youtube,
  };

  const IconComponent = iconMap[name] || LucideIcons.Globe;

  return <IconComponent className={cn("h-4 w-4", className)} />;
}
