import * as LucideIcons from "lucide-react";
import {
  SiGithub, SiGitlab, SiBitbucket, SiJira, SiConfluence, SiTrello,
  SiSlack, SiDiscord, SiZoom,
  SiGooglecloud, SiDigitalocean, SiCloudflare, SiHeroku, SiVercel, SiNetlify,
  SiDocker, SiKubernetes, SiJenkins, SiCircleci, SiTravisci, SiAnsible, SiTerraform, SiPuppet, SiChef, SiArgo,
  SiNpm, SiYarn, SiPnpm, SiBun, SiNodedotjs, SiPython, SiJavascript, SiGo, SiRust, SiPhp, SiRuby, SiDotnet, SiTypescript,
  SiReact, SiVuedotjs, SiAngular, SiSvelte, SiNextdotjs, SiNuxtdotjs,
  SiIntellijidea, SiVim, SiNeovim,
  SiMongodb, SiPostgresql, SiMysql, SiRedis, SiElasticsearch, SiApachecassandra, SiAmazondynamodb,
  SiGrafana, SiPrometheus, SiDatadog, SiSplunk, SiKibana,
  SiGoogledrive, SiDropbox, SiBox, SiBackblaze, SiMinio,
  SiNotion, SiFigma, SiMiro, SiAirtable, SiAsana, SiLinear,
  SiStripe, SiPaypal, SiShopify,
  SiX, SiLinkedin, SiFacebook, SiInstagram, SiYoutube, SiTiktok, SiReddit,
  SiSpotify, SiNetflix, SiTwitch, SiSteam, SiYcombinator,
  SiApple, SiGoogle, SiAmazon,
  SiRss, SiHelm, SiMattermost,
  SiAmazons3, SiAmazonec2, SiAwslambda
} from "react-icons/si";
import { cn } from "@/lib/utils";

interface DynamicIconProps {
  name: string;
  className?: string;
}

export function DynamicIcon({ name, className }: DynamicIconProps) {
  const iconMap: Record<string, React.ElementType> = {
    // DevOps & CI/CD
    Github: SiGithub,
    Gitlab: SiGitlab,
    Bitbucket: SiBitbucket,
    Jira: SiJira,
    Confluence: SiConfluence,
    Jenkins: SiJenkins,
    CircleCi: SiCircleci,
    TravisCi: SiTravisci,
    Ansible: SiAnsible,
    Terraform: SiTerraform,
    Puppet: SiPuppet,
    Chef: SiChef,
    ArgoCD: SiArgo,
    GitOps: SiArgo,
    Pipeline: LucideIcons.Workflow,
    Workflow: LucideIcons.Workflow,
    GitBranch: LucideIcons.GitBranch,
    GitMerge: LucideIcons.GitMerge,
    GitPullRequest: LucideIcons.GitPullRequest,
    GitCommit: LucideIcons.GitCommit,
    
    // Cloud & Infrastructure
    Aws: SiAmazon,
    Azure: LucideIcons.Cloud,
    GoogleCloud: SiGooglecloud,
    DigitalOcean: SiDigitalocean,
    Cloudflare: SiCloudflare,
    Heroku: SiHeroku,
    Vercel: SiVercel,
    Netlify: SiNetlify,
    Cloud: LucideIcons.Cloud,
    CloudUpload: LucideIcons.CloudUpload,
    CloudDownload: LucideIcons.CloudDownload,
    Server: LucideIcons.Server,
    ServerCog: LucideIcons.ServerCog,
    ServerCrash: LucideIcons.ServerCrash,
    Datacenter: LucideIcons.Server,
    Rack: LucideIcons.Server,
    Region: LucideIcons.Globe,
    Zone: LucideIcons.MapPin,
    
    // Containers & Orchestration
    Docker: SiDocker,
    Kubernetes: SiKubernetes,
    Helm: SiHelm,
    Container: LucideIcons.Container,
    Blocks: LucideIcons.Blocks,
    Layers: LucideIcons.Layers,
    Pod: LucideIcons.Box,
    Deployment: LucideIcons.Rocket,
    Service: LucideIcons.Network,
    Namespace: LucideIcons.FolderTree,
    
    // Storage & Databases
    Database: LucideIcons.Database,
    HardDrive: LucideIcons.HardDrive,
    Disc: LucideIcons.Disc,
    Archive: LucideIcons.Archive,
    Folder: LucideIcons.Folder,
    FolderOpen: LucideIcons.FolderOpen,
    FolderTree: LucideIcons.FolderTree,
    S3: SiAmazons3,
    Blob: LucideIcons.FileArchive,
    FileStorage: LucideIcons.Files,
    ObjectStorage: LucideIcons.Box,
    Mongodb: SiMongodb,
    Postgresql: SiPostgresql,
    Mysql: SiMysql,
    Redis: SiRedis,
    Elasticsearch: SiElasticsearch,
    Cassandra: SiApachecassandra,
    DynamoDB: SiAmazondynamodb,
    Vault: LucideIcons.Lock,
    Bucket: LucideIcons.Cylinder,
    
    // Compute & Processing
    Cpu: LucideIcons.Cpu,
    Gpu: LucideIcons.Cpu,
    Memory: LucideIcons.MemoryStick,
    Chip: LucideIcons.Cpu,
    Circuit: LucideIcons.CircuitBoard,
    Processor: LucideIcons.Cpu,
    Lambda: SiAwslambda,
    Function: LucideIcons.FunctionSquare,
    Compute: SiAmazonec2,
    Instance: SiAmazonec2,
    VirtualMachine: LucideIcons.Monitor,
    
    // Network & Security
    Network: LucideIcons.Network,
    Router: LucideIcons.Router,
    Wifi: LucideIcons.Wifi,
    Globe: LucideIcons.Globe,
    Link: LucideIcons.Link,
    ExternalLink: LucideIcons.ExternalLink,
    Share: LucideIcons.Share,
    LoadBalancer: LucideIcons.Scale,
    Gateway: LucideIcons.DoorOpen,
    Firewall: LucideIcons.ShieldBan,
    Cdn: LucideIcons.Globe,
    Dns: LucideIcons.AtSign,
    Proxy: LucideIcons.ArrowLeftRight,
    Vpn: LucideIcons.Lock,
    Lock: LucideIcons.Lock,
    Unlock: LucideIcons.Unlock,
    Key: LucideIcons.Key,
    KeyRound: LucideIcons.KeyRound,
    Shield: LucideIcons.Shield,
    ShieldCheck: LucideIcons.ShieldCheck,
    ShieldAlert: LucideIcons.ShieldAlert,
    Fingerprint: LucideIcons.Fingerprint,
    Scan: LucideIcons.ScanLine,
    Bug: LucideIcons.Bug,
    BugOff: LucideIcons.BugOff,
    
    // Monitoring & Logging
    Activity: LucideIcons.Activity,
    BarChart: LucideIcons.BarChart,
    PieChart: LucideIcons.PieChart,
    LineChart: LucideIcons.LineChart,
    TrendingUp: LucideIcons.TrendingUp,
    TrendingDown: LucideIcons.TrendingDown,
    Grafana: SiGrafana,
    Prometheus: SiPrometheus,
    Datadog: SiDatadog,
    Splunk: SiSplunk,
    Kibana: SiKibana,
    Loki: LucideIcons.FileText,
    AlertCircle: LucideIcons.AlertCircle,
    AlertTriangle: LucideIcons.AlertTriangle,
    Bell: LucideIcons.Bell,
    BellRing: LucideIcons.BellRing,
    Gauge: LucideIcons.Gauge,
    Meter: LucideIcons.Gauge,
    Heartbeat: LucideIcons.HeartPulse,
    
    // Development Tools
    Code: LucideIcons.Code,
    Terminal: LucideIcons.Terminal,
    TerminalSquare: LucideIcons.TerminalSquare,
    Braces: LucideIcons.Braces,
    FileCode: LucideIcons.FileCode,
    FileJson: LucideIcons.FileJson,
    Npm: SiNpm,
    Yarn: SiYarn,
    Pnpm: SiPnpm,
    Bun: SiBun,
    Nodejs: SiNodedotjs,
    Python: SiPython,
    Java: SiJavascript,
    Javascript: SiJavascript,
    Typescript: SiTypescript,
    Go: SiGo,
    Rust: SiRust,
    Php: SiPhp,
    Ruby: SiRuby,
    Dotnet: SiDotnet,
    React: SiReact,
    Vue: SiVuedotjs,
    Angular: SiAngular,
    Svelte: SiSvelte,
    Nextjs: SiNextdotjs,
    Nuxt: SiNuxtdotjs,
    Vscode: LucideIcons.Code,
    Intellij: SiIntellijidea,
    Vim: SiVim,
    Neovim: SiNeovim,
    
    // Collaboration & Communication
    Slack: SiSlack,
    Discord: SiDiscord,
    Teams: LucideIcons.Users,
    Zoom: SiZoom,
    Meet: SiGoogle,
    Mattermost: SiMattermost,
    Notion: SiNotion,
    Trello: SiTrello,
    Asana: SiAsana,
    Linear: SiLinear,
    Monday: LucideIcons.CalendarDays,
    Figma: SiFigma,
    Miro: SiMiro,
    Airtable: SiAirtable,
    Mail: LucideIcons.Mail,
    MessageSquare: LucideIcons.MessageSquare,
    Send: LucideIcons.Send,
    Inbox: LucideIcons.Inbox,
    Users: LucideIcons.Users,
    User: LucideIcons.User,
    UserPlus: LucideIcons.UserPlus,
    
    // General
    Home: LucideIcons.Home,
    Star: LucideIcons.Star,
    Heart: LucideIcons.Heart,
    Bookmark: LucideIcons.Bookmark,
    File: LucideIcons.File,
    FileText: LucideIcons.FileText,
    ClipboardList: LucideIcons.ClipboardList,
    Calendar: LucideIcons.Calendar,
    Clock: LucideIcons.Clock,
    MapPin: LucideIcons.MapPin,
    Navigation: LucideIcons.Navigation,
    Compass: LucideIcons.Compass,
    Map: LucideIcons.Map,
    Settings: LucideIcons.Settings,
    Cog: LucideIcons.Cog,
    Wrench: LucideIcons.Wrench,
    Hammer: LucideIcons.Hammer,
    Tool: LucideIcons.Wrench,
    Zap: LucideIcons.Zap,
    Flame: LucideIcons.Flame,
    Sun: LucideIcons.Sun,
    Moon: LucideIcons.Moon,
    Coffee: LucideIcons.Coffee,
    Book: LucideIcons.Book,
    Newspaper: LucideIcons.Newspaper,
    List: LucideIcons.List,
    Grid: LucideIcons.Grid3X3,
    Search: LucideIcons.Search,
    Eye: LucideIcons.Eye,
    Edit: LucideIcons.Edit,
    Trash: LucideIcons.Trash2,
    Plus: LucideIcons.Plus,
    Check: LucideIcons.Check,
    Download: LucideIcons.Download,
    Upload: LucideIcons.Upload,
    Refresh: LucideIcons.RefreshCw,
    Package: LucideIcons.Package,
    Box: LucideIcons.Box,
    Cube: LucideIcons.Box,
    Hexagon: LucideIcons.Hexagon,
    Hand: LucideIcons.Hand,
    Pointer: LucideIcons.Pointer,
    MousePointer: LucideIcons.MousePointer,
    Monitor: LucideIcons.Monitor,
    MonitorSmartphone: LucideIcons.MonitorSmartphone,
    Tv: LucideIcons.Tv,
    Tablet: LucideIcons.Tablet,
    Smartphone: LucideIcons.Smartphone,
    Touchscreen: LucideIcons.MonitorSmartphone,
    Nas: LucideIcons.HardDrive,
    ServerStack: LucideIcons.Server,
    
    // Payment & Commerce
    Stripe: SiStripe,
    Paypal: SiPaypal,
    Shopify: SiShopify,
    CreditCard: LucideIcons.CreditCard,
    DollarSign: LucideIcons.DollarSign,
    Wallet: LucideIcons.Wallet,
    ShoppingCart: LucideIcons.ShoppingCart,
    Store: LucideIcons.Store,
    Building: LucideIcons.Building,
    Receipt: LucideIcons.Receipt,
    Invoice: LucideIcons.FileText,
    
    // Social & Media
    Twitter: SiX,
    Linkedin: SiLinkedin,
    Facebook: SiFacebook,
    Instagram: SiInstagram,
    Youtube: SiYoutube,
    Tiktok: SiTiktok,
    Spotify: SiSpotify,
    Netflix: SiNetflix,
    Twitch: SiTwitch,
    Steam: SiSteam,
    Reddit: SiReddit,
    HackerNews: SiYcombinator,
    Music: LucideIcons.Music,
    Video: LucideIcons.Video,
    Image: LucideIcons.Image,
    Camera: LucideIcons.Camera,
    Mic: LucideIcons.Mic,
    Headphones: LucideIcons.Headphones,
    
    // Storage Services
    GoogleDrive: SiGoogledrive,
    OneDrive: LucideIcons.Cloud,
    Dropbox: SiDropbox,
    Backblaze: SiBackblaze,
    Wasabi: LucideIcons.Cloud,
    Minio: SiMinio,
    
    // Legacy mappings
    Apple: SiApple,
    Google: SiGoogle,
    Amazon: SiAmazon,
    Microsoft: LucideIcons.Monitor,
    Rss: SiRss,
    Api: LucideIcons.Webhook,
    Webhook: LucideIcons.Webhook,
    Ssh: LucideIcons.KeyRound,
    Ftp: LucideIcons.FolderSync,
    Lightning: LucideIcons.Zap,
    Laptop: LucideIcons.Laptop,
    Truck: LucideIcons.Truck,
    Plane: LucideIcons.Plane,
    Car: LucideIcons.Car,
    Award: LucideIcons.Award,
    Target: LucideIcons.Target,
    Gift: LucideIcons.Gift,
  };

  const IconComponent = iconMap[name] || LucideIcons.Globe;

  return <IconComponent className={cn("h-4 w-4", className)} />;
}
