import * as LucideIcons from "lucide-react";
import {
  SiGithub, SiGitlab, SiBitbucket, SiJira, SiConfluence, SiTrello,
  SiSlack, SiDiscord, SiZoom,
  SiGooglecloud, SiDigitalocean, SiCloudflare,
  SiDocker, SiKubernetes, SiJenkins, SiCircleci, SiTravisci,
  SiNpm, SiYarn, SiNodedotjs, SiPython, SiJavascript, SiGo, SiRust, SiPhp,
  SiReact, SiVuedotjs, SiAngular, SiSvelte, SiNextdotjs,
  SiMongodb, SiPostgresql, SiMysql, SiRedis, SiElasticsearch,
  SiGoogledrive, SiDropbox, SiBox,
  SiNotion, SiFigma, SiMiro, SiAirtable,
  SiStripe, SiPaypal, SiShopify,
  SiX, SiLinkedin, SiFacebook, SiInstagram, SiYoutube, SiTiktok,
  SiSpotify, SiNetflix, SiTwitch, SiSteam,
  SiApple, SiGoogle, SiAmazon,
  SiRss
} from "react-icons/si";
import type { IconName } from "@shared/schema";
import { cn } from "@/lib/utils";

interface DynamicIconProps {
  name: IconName | string;
  className?: string;
}

export function DynamicIcon({ name, className }: DynamicIconProps) {
  const iconMap: Record<string, React.ElementType> = {
    // General Lucide icons
    Globe: LucideIcons.Globe,
    Home: LucideIcons.Home,
    Star: LucideIcons.Star,
    Heart: LucideIcons.Heart,
    Bookmark: LucideIcons.Bookmark,
    Folder: LucideIcons.Folder,
    File: LucideIcons.File,
    Code: LucideIcons.Code,
    Terminal: LucideIcons.Terminal,
    Database: LucideIcons.Database,
    Server: LucideIcons.Server,
    Cloud: LucideIcons.Cloud,
    Monitor: LucideIcons.Monitor,
    Smartphone: LucideIcons.Smartphone,
    Laptop: LucideIcons.Laptop,
    Wifi: LucideIcons.Wifi,
    Lock: LucideIcons.Lock,
    Key: LucideIcons.Key,
    Shield: LucideIcons.Shield,
    Settings: LucideIcons.Settings,
    Cog: LucideIcons.Cog,
    Tool: LucideIcons.Wrench,
    Wrench: LucideIcons.Wrench,
    Hammer: LucideIcons.Hammer,
    Zap: LucideIcons.Zap,
    Lightning: LucideIcons.Zap,
    Flame: LucideIcons.Flame,
    Sun: LucideIcons.Sun,
    Moon: LucideIcons.Moon,
    CloudSun: LucideIcons.CloudSun,
    Music: LucideIcons.Music,
    Video: LucideIcons.Video,
    Image: LucideIcons.Image,
    Camera: LucideIcons.Camera,
    Mic: LucideIcons.Mic,
    Headphones: LucideIcons.Headphones,
    Speaker: LucideIcons.Speaker,
    Mail: LucideIcons.Mail,
    MessageSquare: LucideIcons.MessageSquare,
    Send: LucideIcons.Send,
    Inbox: LucideIcons.Inbox,
    Bell: LucideIcons.Bell,
    Calendar: LucideIcons.Calendar,
    Clock: LucideIcons.Clock,
    MapPin: LucideIcons.MapPin,
    Navigation: LucideIcons.Navigation,
    Compass: LucideIcons.Compass,
    Map: LucideIcons.Map,
    Users: LucideIcons.Users,
    User: LucideIcons.User,
    UserPlus: LucideIcons.UserPlus,
    Building: LucideIcons.Building,
    Store: LucideIcons.Store,
    ShoppingCart: LucideIcons.ShoppingCart,
    CreditCard: LucideIcons.CreditCard,
    DollarSign: LucideIcons.DollarSign,
    Wallet: LucideIcons.Wallet,
    TrendingUp: LucideIcons.TrendingUp,
    BarChart: LucideIcons.BarChart,
    PieChart: LucideIcons.PieChart,
    Activity: LucideIcons.Activity,
    Target: LucideIcons.Target,
    Award: LucideIcons.Award,
    Gift: LucideIcons.Gift,
    Package: LucideIcons.Package,
    Truck: LucideIcons.Truck,
    Plane: LucideIcons.Plane,
    Car: LucideIcons.Car,
    Bike: LucideIcons.Bike,
    Train: LucideIcons.Train,
    Coffee: LucideIcons.Coffee,
    Utensils: LucideIcons.Utensils,
    Pizza: LucideIcons.Pizza,
    Apple: LucideIcons.Apple,
    Leaf: LucideIcons.Leaf,
    Tree: LucideIcons.Trees,
    Flower: LucideIcons.Flower,
    Book: LucideIcons.Book,
    Newspaper: LucideIcons.Newspaper,
    FileText: LucideIcons.FileText,
    ClipboardList: LucideIcons.ClipboardList,
    CheckSquare: LucideIcons.CheckSquare,
    List: LucideIcons.List,
    Grid: LucideIcons.Grid3X3,
    Layers: LucideIcons.Layers,
    Cube: LucideIcons.Box,
    Hexagon: LucideIcons.Hexagon,
    Circle: LucideIcons.Circle,
    Square: LucideIcons.Square,
    Triangle: LucideIcons.Triangle,
    Link: LucideIcons.Link,
    ExternalLink: LucideIcons.ExternalLink,
    Share: LucideIcons.Share,
    Download: LucideIcons.Download,
    Upload: LucideIcons.Upload,
    Refresh: LucideIcons.RefreshCw,
    Search: LucideIcons.Search,
    Eye: LucideIcons.Eye,
    EyeOff: LucideIcons.EyeOff,
    Edit: LucideIcons.Edit,
    Trash: LucideIcons.Trash2,
    Plus: LucideIcons.Plus,
    Minus: LucideIcons.Minus,
    X: LucideIcons.X,
    Check: LucideIcons.Check,
    // Cloud & Infrastructure (Lucide)
    CloudUpload: LucideIcons.CloudUpload,
    CloudDownload: LucideIcons.CloudDownload,
    HardDrive: LucideIcons.HardDrive,
    Cpu: LucideIcons.Cpu,
    Router: LucideIcons.Router,
    Network: LucideIcons.Network,
    Container: LucideIcons.Container,
    Blocks: LucideIcons.Blocks,
    TerminalSquare: LucideIcons.TerminalSquare,
    KeyRound: LucideIcons.KeyRound,
    ShieldCheck: LucideIcons.ShieldCheck,
    Bug: LucideIcons.Bug,
    // SSH/FTP/API (Lucide alternatives)
    Ssh: LucideIcons.KeyRound,
    Ftp: LucideIcons.FolderSync,
    Api: LucideIcons.Webhook,
    Webhook: LucideIcons.Webhook,
    Rss: SiRss,
    // Brand icons (react-icons/si)
    Github: SiGithub,
    Gitlab: SiGitlab,
    Bitbucket: SiBitbucket,
    Jira: SiJira,
    Confluence: SiConfluence,
    Trello: SiTrello,
    Slack: SiSlack,
    Discord: SiDiscord,
    Teams: LucideIcons.Users,
    Zoom: SiZoom,
    Aws: SiAmazon,
    Azure: LucideIcons.Cloud,
    GoogleCloud: SiGooglecloud,
    DigitalOcean: SiDigitalocean,
    Cloudflare: SiCloudflare,
    Docker: SiDocker,
    Kubernetes: SiKubernetes,
    Jenkins: SiJenkins,
    CircleCi: SiCircleci,
    TravisCi: SiTravisci,
    Npm: SiNpm,
    Yarn: SiYarn,
    Nodejs: SiNodedotjs,
    Python: SiPython,
    Java: SiJavascript,
    Go: SiGo,
    Rust: SiRust,
    Php: SiPhp,
    React: SiReact,
    Vue: SiVuedotjs,
    Angular: SiAngular,
    Svelte: SiSvelte,
    Nextjs: SiNextdotjs,
    Mongodb: SiMongodb,
    Postgresql: SiPostgresql,
    Mysql: SiMysql,
    Redis: SiRedis,
    Elasticsearch: SiElasticsearch,
    OneDrive: LucideIcons.CloudUpload,
    GoogleDrive: SiGoogledrive,
    Dropbox: SiDropbox,
    Box: SiBox,
    Notion: SiNotion,
    Figma: SiFigma,
    Miro: SiMiro,
    Airtable: SiAirtable,
    Stripe: SiStripe,
    Paypal: SiPaypal,
    Shopify: SiShopify,
    Twitter: SiX,
    Linkedin: SiLinkedin,
    Facebook: SiFacebook,
    Instagram: SiInstagram,
    Youtube: SiYoutube,
    Tiktok: SiTiktok,
    Spotify: SiSpotify,
    Netflix: SiNetflix,
    Twitch: SiTwitch,
    Steam: SiSteam,
    Microsoft: LucideIcons.Monitor,
    Google: SiGoogle,
    Amazon: SiAmazon,
  };

  const IconComponent = iconMap[name] || LucideIcons.Globe;

  return <IconComponent className={cn("h-4 w-4", className)} />;
}
